<?xml version="1.0"?>
<robot
       xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro"
>

    <xacro:property name="pcb_x_size"   value="0.0889"/>
    <xacro:property name="pcb_y_size"   value="0.05715"/>
    <xacro:property name="pcb_z_size"   value="0.0254"/>
    <xacro:property name="pcb_x_offset" value="0.005"/>
    <xacro:property name="pcb_y_offset" value="-0.09715"/>
    <xacro:property name="pcb_z_offset" value="0.05715"/>

    <link name="pcb">
        <inertial>
            <mass value="0.1"/>
            <inertia ixx="1.01" ixy="0.0" ixz="1.01" iyy="3.03" iyz="0.0" izz="2.02"/>
        </inertial>
    
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${pcb_x_size} ${pcb_y_size} ${pcb_z_size}"/>
            </geometry>
            <xacro:material_silver/>
        </visual>
        
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${pcb_x_size} ${pcb_y_size} ${pcb_z_size}"/>
            </geometry>
            <contact_coefficients mu="0.1" kp="1000.0" kd="1.0"/>
        </collision>
    </link>

    <joint name="base_link_to_pcb" type="fixed">
        <parent link="base_link"/>
        <child link="pcb"/>
        <origin xyz="${pcb_x_offset+pcb_x_size/2} ${pcb_y_offset+pcb_y_size/2} ${pcb_z_offset+pcb_z_size/2}" rpy="0 0 0"/>
    </joint>
</robot>
